# Generated by Django 5.2 on 2025-05-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.TextField(blank=True, null=True)),
                ('data_acquisto', models.TextField()),
                ('data_viaggio', models.TextField()),
                ('prezzo', models.FloatField()),
                ('tipo_biglietto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Biglietto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metodopagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
                ('numero_carta', models.TextField(blank=True, null=True)),
                ('scadenza', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MetodoPagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('citta', models.TextField()),
            ],
            options={
                'db_table': 'Stazione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durata', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tratta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('tipo', models.TextField()),
                ('richiede_nominativo', models.IntegerField()),
            ],
            options={
                'db_table': 'Treno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trenostazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orario_arrivo', models.TextField(blank=True, null=True)),
                ('orario_partenza', models.TextField(blank=True, null=True)),
                ('ordine_di_passaggio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TrenoStazione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cognome', models.TextField()),
                ('codicefiscale', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('username', models.TextField()),
                ('pwd', models.TextField()),
            ],
            options={
                'db_table': 'Utente',
                'managed': False,
            },
        ),
    ]
