# Generated by Django 5.2 on 2025-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trattastazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField()),
                ('orario_arrivo', models.TimeField(blank=True, null=True)),
                ('orario_partenza', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TrattaStazione',
                'managed': False,
            },
        ),
    ]
