# Generated by Django 5.2.4 on 2025-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('eventdate', models.DateField(db_column='EventDate')),
                ('location', models.TextField(db_column='Location')),
                ('guestsnumber', models.IntegerField(db_column='GuestsNumber')),
                ('notes', models.TextField(db_column='Notes')),
            ],
            options={
                'db_table': 'Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('city', models.TextField(db_column='City')),
                ('street', models.TextField(db_column='Street')),
                ('phone', models.TextField(db_column='Phone', unique=True)),
                ('email', models.TextField(db_column='Email', unique=True)),
                ('totrooms', models.IntegerField(db_column='TotRooms')),
            ],
            options={
                'db_table': 'Hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotelrooms',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('roomnumber', models.TextField(db_column='RoomNumber')),
                ('status', models.TextField(db_column='Status')),
                ('type', models.TextField(db_column='Type')),
            ],
            options={
                'db_table': 'HotelRooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('city', models.TextField(db_column='City')),
                ('street', models.TextField(db_column='Street')),
                ('closingdays', models.TextField(db_column='ClosingDays')),
                ('openingdays', models.TextField(db_column='OpeningDays')),
                ('closingtime', models.TimeField(db_column='ClosingTime')),
                ('openingtime', models.TimeField(db_column='OpeningTime')),
                ('phone', models.TextField(db_column='Phone', unique=True)),
                ('email', models.TextField(db_column='Email', unique=True)),
                ('tottables', models.IntegerField(db_column='TotTables')),
            ],
            options={
                'db_table': 'Restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restauranttable',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.TextField(db_column='Status')),
                ('position', models.TextField(db_column='Position')),
                ('tablenumber', models.IntegerField(db_column='TableNumber')),
            ],
            options={
                'db_table': 'RestaurantTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roomreservation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('checkindate', models.DateField(db_column='CheckInDate')),
                ('checkoutdate', models.DateField(db_column='CheckOutDate')),
                ('peoplenumber', models.IntegerField(db_column='PeopleNumber')),
                ('reservationstatus', models.TextField(db_column='ReservationStatus')),
                ('notes', models.TextField(db_column='Notes')),
            ],
            options={
                'db_table': 'RoomReservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tablereservation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('reservationdate', models.DateField(db_column='ReservationDate')),
                ('reservationtime', models.TimeField(db_column='ReservationTime')),
                ('peoplenumber', models.IntegerField(db_column='PeopleNumber')),
                ('reservationstatus', models.TextField(db_column='ReservationStatus')),
                ('notes', models.TextField(db_column='Notes')),
            ],
            options={
                'db_table': 'TableReservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('surname', models.TextField(db_column='Surname')),
                ('mobilephone', models.TextField(db_column='MobilePhone', unique=True)),
                ('email', models.TextField(db_column='Email', unique=True)),
                ('password', models.TextField(db_column='Password')),
                ('fiscalcode', models.TextField(db_column='FiscalCode')),
                ('datebirth', models.DateField(db_column='DateBirth')),
                ('cityresidence', models.TextField(db_column='CityResidence')),
                ('streetresidence', models.TextField(db_column='StreetResidence')),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
