INSERT INTO Stazione(nome, citta) VALUES
('Roma Termini', 'Roma'),
('Milano Centrale', 'Milano'),
('Firenze Santa Maria Novella', 'Firenze'),
('Napoli Centrale', 'Napoli'),
('Bologna Centrale', 'Bologna'),
('Torino Porta Nuova', 'Torino'),
('Venezia Santa Lucia', 'Venezia'),
('Genova Piazza Principe', 'Genova'),
('Palermo Centrale', 'Palermo'),
('Bari Centrale', 'Bari'),
('Verona Porta Nuova', 'Verona'),
('Pisa Centrale', 'Pisa'),
('Lecce', 'Lecce'),
('Trieste Centrale', 'Trieste'),
('Catania Centrale', 'Catania'),
('Messina Centrale', 'Messina'),
('Salerno', 'Salerno'),
('Reggio Calabria Centrale', 'Reggio Calabria'),
('Ancona', 'Ancona'),
('Padova', 'Padova'),
('Parma', 'Parma'),
('Perugia', 'Perugia'),
('Bergamo', 'Bergamo'),
('Rimini', 'Rimini'),
('Siena', 'Siena'),
('Livorno Centrale', 'Livorno'),
('Modena', 'Modena'),
('Piacenza', 'Piacenza'),
('Como San Giovanni', 'Como'),
('Pescara Centrale', 'Pescara'),
('La Spezia Centrale', 'La Spezia'),
('Cagliari', 'Cagliari'),
('Taranto', 'Taranto'),
('Vicenza', 'Vicenza'),
('Aquila', 'Aquila'),
('Ferrara', 'Ferrara'),
('Lucca', 'Lucca'),
('Orvieto', 'Orvieto'),
('Ascoli Piceno', 'Ascoli Piceno'),
('Foggia', 'Foggia'),
('Catanzaro Lido', 'Catanzaro'),
('Terni', 'Terni'),
('Matera', 'Matera'),
('Trapani', 'Trapani'),
('Sorrento', 'Sorrento'),
('Cosenza', 'Cosenza'),
('Avellino', 'Avellino'),
('Vibo Valentia', 'Vibo Valentia');