INSERT Stazione(nome, citta) VALUES
(Milano Centrale, Milano),
(Roma Termini, Roma),
(Napoli Centrale, Napoli),
(Torino Porta Nuova, Torino),
(Firenze Santa Maria Novella, Firenze),
(Venezia Santa Lucia, Venezia),
(Bologna Centrale, Bologna),
(Verona Porta Nuova, Verona),
(Genova Piazza Principe, Genova),
(Palermo Centrale, Palermo),
(Bari Centrale, Bari),
(Reggio Calabria Centrale, Reggio Calabria),
(Trieste Centrale, Trieste),
(Catania Centrale, Catania),
(Salerno, Salerno),
(Padova, Padova),
(Parma, Parma),
(Pisa Centrale, Pisa),
(Perugia, Perugia),
(Ancona, Ancona);