# Generated by Django 5.1.7 on 2025-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_site_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('ChatBot', 'ChatBot'), ('TTI', 'Text-To-Image'), ('TTV', 'Text-To-Video')], max_length=64),
        ),
    ]
