# Generated by Django 5.2.5 on 2025-08-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_site_slug_alter_site_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('ChatBot', 'ChatBot'), ('TextToImage', 'Text-To-Image'), ('TextToVideo', 'Text-To-Video'), ('Info', 'Info'), ('TextToAudio', 'Text-To-Audio'), ('SpeechToText', 'Speech-To-Text'), ('PromptGenerator', 'Prompt-Generator'), ('EditorEditing', 'Editor-Editing'), ('Animation3D', 'Animation3D'), ('Presentation', 'Presentation'), ('Analyses', 'Analyses'), ('Copywriting', 'Copywriting'), ('AppCreator', 'AppCreator'), ('Management', 'Management'), ('ContentIdeas', 'ContentIdeas'), ('ImageEnhancer', 'Image Enhancer'), ('VideoEnhancer', 'Video Enhancer'), ('Translation', 'Translation'), ('CodeGenerator', 'Code Generator'), ('DataAnalysis', 'Data Analysis'), ('Marketing', 'Marketing Tools'), ('SocialMedia', 'Social Media'), ('EmailAssistant', 'Email Assistant'), ('ResumeTools', 'Resume Tools'), ('Education', 'Education'), ('GameDev', 'Game Development'), ('Productivity', 'Productivity'), ('Security', 'Security'), ('Finance', 'Finance & Investing'), ('Legal', 'Legal Assistance')], max_length=64),
        ),
    ]
